import toolforge
import pymysql
from galobotbase import *

conn = toolforge.connect('enwiki')

tablerows = []
with conn.cursor(pymysql.cursors.DictCursor) as cur:
    cur.execute("select page_title, count(*) from linter join page on page.page_id = linter.linter_page where page.page_namespace=0 group by page.page_id order by count(*) desc limit 1000;")
    data = cur.fetchall()
    for row in data:
        tablerows.append('\n|-\n| [[' + row['page_title'].decode().replace('_', ' ') + ']]\n|' + str(row['count(*)']))
    
    page = p.Page(site, 'User:Galobot/report/Articles_by_Lint_Errors')
    page.text = 'Generated by [[Quarry:query/30386|this query]]. Updated on ~~~~~. \n{| class="wikitable sortable"\n!page title\n!lint errors' + "".join(tablerows) + "\n|}"
    page.savewithshutoff(summary = 'Update "Articles by Lint Errors" report') #edit page
